---

  - name: Software properties common
    apt:
      name:
        - software-properties-common
      update_cache: yes
      state: latest

  - name: Add repository
    apt_repository:
      repo: ppa:vbernat/haproxy-1.5

  - name: Install HAProxy
    apt:
      name:
        - haproxy
      update_cache: yes
      state: latest
