---

- name: Run consul on first master
  hosts: master[0]
  tasks:
    - shell: consul agent -config-dir /etc/consul.d/services -config-file consul_server.json >> /dev/null &
      args:
        chdir: "{{ ansible_env.HOME }}"

- name: Run consul on the rest of the masters
  hosts: master:!master[0]
  tasks:
    - shell: consul agent -config-dir /etc/consul.d/services -config-file consul_server.json -join {{ groups['master'][0]}} >> /dev/null &
      args:
        chdir: "{{ ansible_env.HOME }}"

- name: Run consul on the clients
  hosts: private:public
  tasks:
    - shell: consul agent -config-dir /etc/consul.d/services -config-file consul_client.json -join {{ groups['master'][0]}} >> /dev/null &
      args:
        chdir: "{{ ansible_env.HOME }}"

- name: Register Nomad as a Consul service
  hosts: all
  become: yes
  tasks:
  - name: Copy service config file
    copy:
      src: ../Config/consul_nomad_service.json
      dest:  /etc/consul.d/services
  - name: Config Consul client config
    consulconf:
      file: consul_nomad_service.json
      path: /etc/consul.d/services
      address: "{{ ansible_all_ipv4_addresses[1] }}"
      service_name: Nomad
      check_id: nomadcheck
      check_name: Nomad on port 4646
      check_http: http://{{ ansible_all_ipv4_addresses[1] }}/v1/nodes
  - name: Reload Consul
    command: consul reload
