---

  - name: Stop previous Consul
    hosts: all
    tasks:
      - include: tasks/stop_consul.yml

  - name: Run Consul on first master
    hosts: master[0]
    tasks:
      - shell: consul agent -config-dir /etc/consul.d/services -config-file consul_server.json >> /dev/null &
        args:
          chdir: "{{ ansible_env.HOME }}"
        register: command_result
        failed_when: "command_result.stderr"

  - name: Run Consul on the rest of the masters
    hosts: master:!master[0]
    tasks:
      - name: Waiting for first master
        wait_for:
          host: "{{ groups['master'][0] }}"
          port: 8301 # Consul RPC port
          timeout: 10
      - shell: consul agent -config-dir /etc/consul.d/services -config-file consul_server.json -join {{ groups['master'][0]}} >> /dev/null &
        args:
          chdir: "{{ ansible_env.HOME }}"
        register: command_result
        failed_when: "command_result.stderr"
  - name: Run Consul on the clients
    hosts: private:public
    tasks:
      - name: Waiting for masters
        with_inventory_hostnames: master
        wait_for:
          host: "{{ item }}"
          port: 8301 # Consul RPC port
          timeout: 10
      - shell: consul agent -config-dir /etc/consul.d/services -config-file consul_client.json -join {{ groups['master'][0]}} >> /dev/null &
        args:
          chdir: "{{ ansible_env.HOME }}"
        register: command_result
        failed_when: "command_result.stderr"
