---

  - name: Install Nomad + Consul
    hosts: all
    # remote_user:
    become: yes # sudo
    roles:
      - Consul
      - Nomad
  - name: Install Executor
    hosts: all:!master
    become: yes
    roles:
      - Docker
      - Python-consul # Requirements for consul module of Ansible
  - include: update_config.yml
  - include: run_consul.yml
  - include: run_nomad.yml
