---

- hosts: master
  remote_user: antonio
  tasks:
  - name: Copy Nomad server config
    copy:
      src: ../Config/nomad_server.json
      dest:  {{ansible_env.HOME}}
  - name: Copy Consul server config
    copy:
      src: ../Config/consul_server.json
      dest:  {{ansible_env.HOME}}
  - name: Update Nomad master configs
    json_mod:
      path: "nomad_server.json"
      username: {{ansible__nodename}}
  - name: Update Consul master configs
    json_mod:
      path: "consul_server.json"

- hosts: clients
  remote_user: antonio
  tasks:
  - name: Copy Nomad client config
    copy:
      src: ../Config/nomad_client.json
      dest:  {{ansible_env.HOME}}
  - name: Copy Consul client config
    copy:
      src: ../Config/consul_client.json
      dest:  {{ansible_env.HOME}}
  - name: Update Nomad clients configs
    json_mod:
      path: "nomad_client.json"
  - name: Update Consul clients configs
    json_mod:
      path: "consul_client.json"
