---

- name: Update Master Configuration files
  hosts: master
  remote_user: antonio
  tasks:
  - name: Copy Nomad server config
    copy:
      src: ../Config/nomad_server.json
      dest:  "{{ ansible_env.HOME }}"
  - name: Copy Consul server config
    copy:
      src: ../Config/consul_server.json
      dest:  "{{ ansible_env.HOME }}"
  - name: Update Nomad master configs
    json:
      file: nomad_server.json
      path: "{{ ansible_env.HOME }}"
      url: "{{ ansible_default_ipv4.address }}"
      key: name
      name: "{{ ansible_nodename }}"
  - name: Update Consul master configs
    json:
      file: consul_server.json
      path: "{{ ansible_env.HOME }}"
      url: "{{ ansible_default_ipv4.address }}"
      key: node_name
      name: "{{ ansible_nodename }}"

- name: Copy Clients Configuration files
  hosts: public:private
  remote_user: antonio
  tasks:
  - name: Copy Nomad client config
    copy:
      src: ../Config/nomad_client.json
      dest:  "{{ ansible_env.HOME }}"
  - name: Copy Consul client config
    copy:
      src: ../Config/consul_client.json
      dest:  "{{ ansible_env.HOME }}"
  - name: Update Consul clients configs
    json:
      file: consul_client.json
      path: "{{ ansible_env.HOME }}"
      url: "{{ ansible_default_ipv4.address }}"
      key: node_name
      name: "{{ ansible_nodename }}"

- name: Update public nodes
  hosts: public
  remote_user: antonio
  tasks:
  - name: Update Nomad public clients configs
    json:
      file: nomad_client.json
      path: "{{ ansible_env.HOME }}"
      url: "{{ ansible_default_ipv4.address }}"
      key: name
      name: "{{ ansible_nodename }}"
      node_class: Public

- name: Update private nodes
  hosts: private
  remote_user: antonio
  tasks:
  - name: Update Nomad private clients configs
    json:
      file: nomad_client.json
      path: "{{ ansible_env.HOME }}"
      url: "{{ ansible_default_ipv4.address }}"
      key: name
      name: "{{ ansible_nodename }}"
      node_class: Private
