---
  
- name: Install unzip
  apt:
    name:
      - unzip
    update_cache: yes
    state: latest
- name: Download and unzip Consul
  unarchive:
    src: https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
    dest: /usr/bin
    copy: no
    mode: "a+x"

- name: Create Consul services folder
  file: path=/etc/consul.d/services state=directory mode="a+w"

- name: Create Consul ui folder
  file: path=/etc/consul.d/ui state=directory

- name: Download and unzip Consul UI Web
  unarchive: src=https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_web_ui.zip dest=/etc/consul.d/ui copy=no

- name: Install dnsmasq
  apt:
    name:
      - dnsmasq
    update_cache: yes
    state: latest
- name: Add Consul dns configuration
  command: echo 'server=/consul/127.0.0.1#8600' | sudo tee --append /etc/dnsmasq.d/10-consul
- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
