---

- name: Docker requirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - apparmor
      - linux-image-extra-{{ ansible_kernel }}
    update_cache: yes
    state: latest
- name: Add docker apt keys
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
- name: Update apt repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
- name: Install docker
  apt:
    name: docker-engine
    update_cache: yes
    state: latest
- name: Docker Group
  user:
    name: antonio
    groups: docker
    append: yes
