#!/bin/sh

scale()
{
	python3 scale.py
}

case "$1" in
OK)
	;;
WARNING)
	;;
UNKNOWN)
	;;
CRITICAL)
	echo "Entrando en Critical"
  scale
	echo "Ansible"
	#ansible-playbook -i hosts --extra-vars "ansible_ssh_pass=Reverse1" site.yml
	;;

esac
exit 0
