---
- name: Install unzip
  apt:
    name:
      - unzip
    update_cache: yes
    state: latest

- name: Download and unzip Nomad
  unarchive:
    src: https://releases.hashicorp.com/nomad/0.3.2/nomad_0.3.2_linux_amd64.zip
    dest: /usr/bin
    copy: no
    mode: "a+x"
