---
  - name: Nagios NRPE Server
    become: yes
    apt:
      name:
        - nagios-nrpe-server
        - libssl-dev
      update_cache: yes
      state: latest

  - name: Download NPRE plugin
    unarchive:
      src: http://downloads.sourceforge.net/project/nagios/nrpe-2.x/nrpe-2.15/nrpe-2.15.tar.gz
      dest: /tmp
      copy: no
    register: result
    until: result.rc ==0
    retries: 5
    delay: 10

  - name: Compile NRPE plugin
    become: yes
    shell: "{{ item }}"
    with_items:
      - ./configure --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu >> /dev/null
      - make all
      - make install-plugin
      - make install-daemon
      - make install-daemon-config
    args:
      chdir: /tmp/nrpe-2.15
    ignore_errors: yes

  - name: Copy configuration file
    copy:
      src: nrpe.cfg
      dest: /etc/nagios
      force: yes

  - name: Restar NRPE server
    service:
      name: nagios-nrpe-server
      state: restarted
